######################## default configuration ####################
baseURL = "https://pieinthesky-eden.com"
languageCode = "en"
title = "Pie in the Sky in Eden by Kelly"
theme = "pie-sky"
summaryLength = "20"
paginate = 10
disqusShortname = ""

############################## navigation ###############################
[menu]

[[menu.main]]
name = "Dessert Pies"
URL = "/#fruitpies"
weight = 1

[[menu.main]]
name = "Dinner Pies"
URL = "/#dinnerpies"
weight = 2

[[menu.main]]
name = "Newsletter"
URL = "/#newsletter"
weight = 3

[[menu.main]]
name = "Order"
URL = "/contact"
absurl = false
weight = 4

## multi menu
# [[menu.main]]
# weight = 5
# name = "More"
# hasChildren = true

#      [[menu.main]]
#      parent = "More"
#      name = "Service"
#      url = "service/"
#      weight = 1

#      [[menu.main]]
#      parent = "More"
#      name = "Pricing"
#      url = "pricing/"
#      weight = 2

#      [[menu.main]]
#      parent = "More"
#      name = "FAQ"
#      url = "faq/"
#      weight = 3

############# footer menu #############
# [[menu.footer]]
# name = "Products"
# URL = "products"
# weight = 1

# [[menu.footer]]
# name = "Blog"
# URL = "blog"
# weight = 2

# [[menu.footer]]
# name = "FAQ"
# URL = "faq"
# weight = 3

# [[menu.footer]]
# name = "Terms & Conditions"
# URL = "terms-conditions"
# weight = 4

# [[menu.footer]]
# name = "Contact"
# URL = "contact"
# weight = 5


#################### default parameters ################################
[params]
ccc = "#00CC00"
logo = "images/logo.png"
home = "Home"
# Meta data
description = "Fresh sweet pies and dinner pies made in Eden Utah"
author = "Kelly"
# google map
gmapAPI = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
mapLatitude = "51.5223477"
mapLongitude = "-0.1622023"
mapMarker = "images/marker.png"
# Google Analitycs
googleAnalitycsID = "" # Your ID
# Contact Information
mobile = "801-941-1855"
email = "order@pieinthesky-eden.com"
location = "Eden, UT"
textmsg = "Hi Kelly, here is my pie order for the"
# copyright
copyright = "Copyright &copy; 2021 Pie in The Sky Eden"
enable_social = false
# Snipcart Credentials
snipcartApiKey = "deadbeefdeadbeef"
currencySymbol = "$"
# MailChimp
mailchimpURL="https://pieinthesky-eden.us7.list-manage.com/subscribe/post?u=ec64ff3c588869ba913df4cd1&amp;id=7a5ae3439d"

# Preloader
[params.preloader]
enable = true
preloader = "" # use .png , .svg or .gif format

# Product Rating
# it works with https://rating-widget.com/ , you will get the ID and publicKey after creating your account there.
[params.rating]
enable = true
websiteID = "12345"
publicKey = "deadbeef"

# Social Site
[[params.social]]
icon = "ti-facebook"
link = "#"

[[params.social]]
icon = "ti-twitter-alt"
link = "#"

[[params.social]]
icon = "ti-youtube"
link = "#"

[[params.social]]
icon = "ti-instagram"
link = "#"

[[params.social]]
icon = "ti-pinterest"
link = "#"

# Contact Form
[params.contact]
formAction = "#" # contact form works with formspree.io

############################# Style ##############################
[params.style]
primary_color = "#C6600D"
text_color = "#333333"
text_color_dark = "#222222"
body_color = "#fff"
border_color = "#D1D1D1"
black = "#000"
white = "#fff"
light = "rgb(223, 223, 223)"
gradient = "27deg, rgb(166,98,5) 0%, rgb(214,148,58) 100%" # ThanksGiving
#gradient = "27deg, rgb(194,31,31) 0%, rgb(110,4,7) 100%" # XMas 

############################# Plugins ##############################
[params.plugins]

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"

[[params.plugins.css]]
link = "plugins/slick/slick.css"

[[params.plugins.css]]
link = "plugins/font-awesome/fontawesome.min.css"

[[params.plugins.css]]
link = "plugins/font-awesome/brands.css"

[[params.plugins.css]]
link = "plugins/font-awesome/solid.css"

[[params.plugins.static_css]]
link = "plugins/themify-icons/themify-icons.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"
